//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLynhom7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public string MaSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> DiemCC { get; set; }
        public Nullable<double> DiemThaoLuan { get; set; }
        public Nullable<double> DiemGK { get; set; }
        public Nullable<double> DiemThi { get; set; }
        public Nullable<double> DiemTB { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
