//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLynhom7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public Lop()
        {
            this.SinhViens = new HashSet<SinhVien>();
        }
    
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string MaKhoa { get; set; }
    
        public virtual Khoa Khoa { get; set; }
        public virtual ICollection<SinhVien> SinhViens { get; set; }
    }
}
