//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLynhom7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public SinhVien()
        {
            this.Diems = new HashSet<Diem>();
        }
    
        public string MaSV { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string MaLop { get; set; }
        public Nullable<int> ID_TaiKhoan { get; set; }
    
        public virtual ICollection<Diem> Diems { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
